# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - "3.5"

# command to install dependencies
#install:
#  - pip install -r requirements.txt

# command to run tests
script: nosetests -v
branches:
  only:
    - master
notifications:
  email:
    on_failure: change
    on_succes: never
